In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
# 単純なアレイを用意します。
arr1 = np.arange(9).reshape((3,3))

In [4]:
#show
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
# 2つのアレイを列方向（axis=1）に連結します
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
# 2つのアレイを列方向（axis=1）に連結します
np.concatenate([arr1,arr1])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# pandas.Seriesでやってみます。
ser1 =  Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])
# concatで、デフォルトは axis=0
pd.concat([ser1,ser2,ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [8]:
# 列方向に連結すると、DataFrameが出来ます。
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [9]:
# 階層的なindexを付けてSeriesを連結することもできます。
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [10]:
# 列方向に連結すると、列の名前になります。
pd.concat([ser1,ser2],axis=1,keys=['cat1','cat2'])

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [11]:

# DataFrameでも同じ事ができます。
dframe1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])
dframe2 = DataFrame(np.random.randn(3, 3), columns=['Y', 'Q', 'X'])

In [12]:
#show
dframe1

X         Y         Z
0 -0.541616  0.598810  0.071037
1 -0.722860  1.249344 -0.392625
2  0.028729 -1.639870 -0.725182
3 -0.165342  1.684833  1.173994

In [13]:
#show
dframe2

Y         Q         X
0  0.136532 -0.031177  0.760032
1  0.070808 -0.884183  0.443342
2 -0.818987 -0.083822  0.631562

In [14]:
# DataFrameを連結します。
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -0.541616  0.598810  0.071037
1       NaN -0.722860  1.249344 -0.392625
2       NaN  0.028729 -1.639870 -0.725182
3       NaN -0.165342  1.684833  1.173994
0 -0.031177  0.760032  0.136532       NaN
1 -0.884183  0.443342  0.070808       NaN
2 -0.083822  0.631562 -0.818987       NaN

In [15]:
# もとのindexを無視することもできます。
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN -0.541616  0.598810  0.071037
1       NaN -0.722860  1.249344 -0.392625
2       NaN  0.028729 -1.639870 -0.725182
3       NaN -0.165342  1.684833  1.173994
4 -0.031177  0.760032  0.136532       NaN
5 -0.884183  0.443342  0.070808       NaN
6 -0.083822  0.631562 -0.818987       NaN

In [16]:
# We can specify which specific axes to be used
pd.concat([ser1,ser2],axis=1,join_axes=[['U','V','Y']])

0    1
U  1.0  NaN
V  2.0  NaN
Y  NaN  4.0

In [17]:
#show
ser1

T    0
U    1
V    2
dtype: int64

In [18]:
#show
ser2

X    3
Y    4
dtype: int64

In [ ]:
# 公式ドキュメントはこちらです。
url='http://pandas.pydata.org/pandas-docs/stable/generated/pandas.concat.html'